#ifndef Q09NRSBIRVJFLCBSRVNJREVOVC4gSSBXSUxMIFRSRUFUIFlPVSBXSVRIIEZBQ1RT
#define Q09NRSBIRVJFLCBSRVNJREVOVC4gSSBXSUxMIFRSRUFUIFlPVSBXSVRIIEZBQ1RT

#include "__m__i__n__d__/__g__l__o__r__y__.h"

MOURNFUL_ENTITY __F__A__C__T__
{
WITH_LOVE_AND_OPEN_HEART:
    __F__A__C__T__();

WITH_DIGNITY_AND_SELF_RESPECT:
    THE_LOVED_ONE ADAPTABLE PREACHING(GODLY::DISPLAY & __, UNSHAKEN __F__A__C__T__ & ____)->GODLY::DISPLAY &;
};

#endif
