#define W ░░░█░░█░░█░░░
#define O ░░░▓░░▓░░▓░░░
#define R █░░▒▒▒▓▒▒▒░░█
#define S ▓░░░░░▓░░░░░▓
#define H ▒▒▒▒▓▓▓▓▓▒▒▒▒
#define I ░░░░░░▓░░░░░░
#define P ░░█▓▒▒▓▒▒▓█░░
#define A ░░░░░▓░▓░░░░░
#define B ░░░░▓░░░▓░░░░
#define L ░░░░▓░░░▓░░░░
#define E ░░░░░▓▓▓░░░░░
